#pragma once

#define SENSOR_COUNT 12

#define BOARD_TYPE "fsriov2"
#define BOOTLOADER_ADDRESS "0x7000"

#define FEATURE_LIGHTS_ENABLED
#define FEATURE_LIGHTS_CHANNELS
#define FEATURE_DIGIPOT_ENABLED

#define LED_PANELS 8
#define PANEL_LEDS 8

#define ADC_LAYOUT ADC_LAYOUT_FSRIO_2
